// KIND v7 · sound-synth — the DSP and the cue library behind src/fx/sound.js.
// Split out so first load pays nothing for it (sound.js pulls this chunk in on the first gesture / at idle).
//
// Everything here only *schedules nodes* on whatever BaseAudioContext it is handed, so the very same code
// plays live and renders offline (OfflineAudioContext) for tools/audio-render.mjs. No audio files, no globals.
//
//   cue(ctx, bus, t0, opts)   bus = { dry, send } (GainNodes made by master.bus());  opts = { rate, seed, step, on, final, tier, pan, lite }
//   schedule(ctx, master, cue, at, opts)   one cue on a master: bus + notes + duck. The live engine and every offline render go through it.
//   Cue bodies are written in "design" seconds and Hz. `rate` (opts.rate) is applied by the voice helpers —
//   pitch × rate, time ÷ rate — so a cue never has to think about it.
//
// One sonic world: D major pentatonic (D E F# A B). Every pitched cue lives on it, so any two can overlap
// without clashing. Timbre = glass: sine + octave, a short FM "ting" on the strike, plate reverb behind.

import { MARKS } from './sound-marks.js'

const TAU = Math.PI * 2
const clamp = (x, lo, hi) => Math.min(hi, Math.max(lo, x))

// ── pitch ────────────────────────────────────────────────────────────────────────────────────────
const PENT = [0, 2, 4, 7, 9]               // semitones above D: D E F# A B
const D4 = 440 * 2 ** (-7 / 12)            // 293.66 Hz
/** Degree k of D-pentatonic. 0 = D4, 1 = E4, 2 = F#4, 3 = A4, 4 = B4, 5 = D5 … ; negatives descend (-5 = D3, -10 = D2). */
export const P = (k) => {
  const o = Math.floor(k / 5), i = ((k % 5) + 5) % 5
  return D4 * 2 ** ((o * 12 + PENT[i]) / 12)
}

// ── deterministic noise ──────────────────────────────────────────────────────────────────────────
const prng = (seed) => {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = a
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

const assets = new WeakMap()               // ctx → { noise }
const assetsOf = (ctx) => { let a = assets.get(ctx); if (!a) assets.set(ctx, (a = {})); return a }

// The noise and the impulse responses are generated by resumable generators: a slice every 16k samples, so a phone can spread the work over idle time
// and several ticks (a cold JS engine runs these loops 10-100x slower than a warm one) instead of freezing the first tap. run() finishes one in a single go.
const SLICE = 16383
const run = (gen) => { let r; do r = gen.next(); while (!r.done); return r.value }

/** One channel of the shared noise: 2.5 s of pink noise, seamless when looped, RMS ≈ .25. Pink, not white: whooshes stay warm, clicks stay soft. Pure data (no context needed). */
function* noiseGen(sr, c) {
  const N = Math.floor(sr * 2.5), X = 2048
  const r = prng(1234 + c * 77), raw = new Float32Array(N + X)
  let b0 = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0
  for (let i = 0; i < raw.length; i++) {
    const w = r() * 2 - 1
    b0 = .99886 * b0 + w * .0555179; b1 = .99332 * b1 + w * .0750759; b2 = .969 * b2 + w * .153852
    b3 = .8665 * b3 + w * .3104856;  b4 = .55 * b4 + w * .5329522;   b5 = -.7616 * b5 - w * .016898
    raw[i] = b0 + b1 + b2 + b3 + b4 + b5 + b6 + w * .5362
    b6 = w * .115926
    if ((i & SLICE) === SLICE) yield
  }
  const d = new Float32Array(N)
  for (let i = 0; i < N; i++) d[i] = raw[i]
  for (let i = 0; i < X; i++) {            // equal-power crossfade of the tail into the head → no loop click
    const w = (i / X) * Math.PI / 2
    d[i] = raw[i] * Math.sin(w) + raw[N + i] * Math.cos(w)
  }
  yield
  let e = 0
  for (let i = 0; i < N; i++) e += d[i] * d[i]
  const k = .25 / Math.sqrt(e / N)
  for (let i = 0; i < N; i++) d[i] *= k
  return d
}
const noiseData = (sr, c) => run(noiseGen(sr, c))
function noiseBuf(ctx) {
  const a = assetsOf(ctx)
  if (a.noise) return a.noise
  const sr = ctx.sampleRate, buf = ctx.createBuffer(2, Math.floor(sr * 2.5), sr)
  for (let c = 0; c < 2; c++) buf.copyToChannel(a.noiseData?.[c] || noiseData(sr, c), c)
  return (a.noise = buf)
}

/** One channel of a reverb impulse response: dense decorrelated noise, exponential decay, a tail that darkens as it ages (air absorption), a short pre-delay.
 *  The decay is a running product and the darkening coefficient is refreshed every 64 samples: same sound, a quarter of the cost. */
function* irGen(sr, { rt = 1.7, pre = .014, bright = 9000, dark = 1800 } = {}, c = 0) {
  const p0 = Math.floor(pre * sr), N = Math.floor((rt * 1.08 + pre) * sr), d = new Float32Array(N), r = prng(9001 + c * 313)
  const dec = Math.exp(-6.91 / (rt * sr)), fade = Math.max(1, .005 * sr)
  let y = 0, env = 1, k = 0
  for (let i = p0; i < N; i++) {
    const n = i - p0
    if ((n & 63) === 0) k = 1 - Math.exp(-TAU * (dark + (bright - dark) * Math.exp(-(n / sr) * 2.4)) / sr)
    y += ((r() * 2 - 1) - y) * k
    d[i] = y * env * (n < fade ? n / fade : 1)
    env *= dec
    if ((i & SLICE) === SLICE) yield
  }
  return d
}
const irData = (sr, p, c) => run(irGen(sr, p, c))
const toBuffer = (ctx, ch) => { const b = ctx.createBuffer(ch.length, ch[0].length, ctx.sampleRate); ch.forEach((d, c) => b.copyToChannel(d, c)); return b }

// ── master chain ─────────────────────────────────────────────────────────────────────────────────
/** Soft ceiling: transparent below .6, tanh knee above, asymptote .96 (-0.35 dBFS). Safety net, not a sound. */
const CLIP = (() => {
  const n = 4097, c = new Float32Array(n), k = .6, s = .36
  for (let i = 0; i < n; i++) {
    const x = (i / (n - 1)) * 2 - 1, a = Math.abs(x)
    c[i] = Math.sign(x) * (a <= k ? a : k + s * Math.tanh((a - k) / s))
  }
  return c
})()

/** User volume 0..1 → linear gain. 1 = the level the cues are designed and measured at; .6 (default) ≈ -5.5 dB. */
export const taper = (v) => clamp(+v || 0, 0, 1) ** 1.3

/**
 * sum → 20 Hz DC/sub blocker → volume → soft compressor → ceiling → destination.
 * Two reverbs: a tight glass-box ROOM for UI micro-cues and a PLATE for verdicts, rewards and heroes.
 *   master.bus(gain, kind) → { dry, send, dispose(), fade(sec) }      kind: 'ui' | 'reward' | 'hero'  (hero bypasses the duck — it causes it)
 *   master.duck(depth, sec, at)    master.setVolume(v)    master.probe() → { left, right, comp }: AnalyserNodes on the output + the compressor (a meter for the playground; built on first call)
 */
export function createMaster(ctx, { volume = 1, assets = null, defer = false } = {}) {
  const sum = ctx.createGain()
  const dcb = ctx.createBiquadFilter(); dcb.type = 'highpass'; dcb.frequency.value = 20; dcb.Q.value = .6
  const vol = ctx.createGain(); vol.gain.value = taper(volume)
  const comp = ctx.createDynamicsCompressor()
  comp.threshold.value = -12; comp.knee.value = 20; comp.ratio.value = 4; comp.attack.value = .006; comp.release.value = .22
  const trim = ctx.createGain(); trim.gain.value = TRIM           // cancels the compressor's fixed makeup gain (+1.24 dB, measured; tools/audio-render.mjs re-checks it)
  const clip = ctx.createWaveShaper(); clip.curve = CLIP; clip.oversample = '2x'
  sum.connect(dcb); dcb.connect(vol); vol.connect(comp); comp.connect(trim); trim.connect(clip); clip.connect(ctx.destination)
  let probe = null
  if (assets) assetsOf(ctx).noiseData = assets.noise

  const later = []                                                // defer: convolvers are loaded by the caller, one per tick (each assignment is a ~20 ms FFT on a desktop)
  const verb = (key, ir, hpF, lpF) => {
    const input = ctx.createGain(), conv = ctx.createConvolver()
    const load = () => { conv.buffer = toBuffer(ctx, assets?.[key] || [irData(ctx.sampleRate, ir, 0), irData(ctx.sampleRate, ir, 1)]) }
    if (defer) later.push(load); else load()
    const hp = ctx.createBiquadFilter(); hp.type = 'highpass'; hp.frequency.value = hpF; hp.Q.value = .5
    const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = lpF; lp.Q.value = .5
    input.connect(conv); conv.connect(hp); hp.connect(lp); lp.connect(sum)
    return input
  }
  const plate = verb('plate', PLATE, 240, 6200)
  const room = verb('room', ROOM, 320, 7000)

  const duckDry = ctx.createGain(), duckPlate = ctx.createGain(), duckRoom = ctx.createGain()
  duckDry.connect(sum); duckPlate.connect(plate); duckRoom.connect(room)

  return {
    finish: later,
    bus(gain = 1, kind = 'reward') {
      const dry = ctx.createGain(), send = ctx.createGain()
      dry.gain.value = send.gain.value = gain
      if (kind === 'hero') { dry.connect(sum); send.connect(plate) }
      else { dry.connect(duckDry); send.connect(kind === 'ui' ? duckRoom : duckPlate) }
      return {
        dry, send,
        fade(sec = .12) { const t = ctx.currentTime; for (const g of [dry.gain, send.gain]) { g.cancelScheduledValues(t); g.setTargetAtTime(0, t, sec / 3) } },
        dispose() { try { dry.disconnect(); send.disconnect() } catch { /* already gone */ } },
      }
    },
    setVolume(v) { vol.gain.setTargetAtTime(taper(v), ctx.currentTime, .02) },
    probe() {
      if (!probe) {
        const sp = ctx.createChannelSplitter(2), left = ctx.createAnalyser(), right = ctx.createAnalyser()
        left.fftSize = right.fftSize = 1024; left.smoothingTimeConstant = right.smoothingTimeConstant = 0
        clip.connect(sp); sp.connect(left, 0); sp.connect(right, 1)
        probe = { left, right, comp }
      }
      return probe
    },
    duck(depth = .45, sec = 1, at = ctx.currentTime) {
      for (const g of [duckDry.gain, duckPlate.gain, duckRoom.gain]) {
        g.cancelScheduledValues(at)
        g.setTargetAtTime(depth, at, .03)
        g.setTargetAtTime(1, at + sec, .22)
      }
    },
  }
}
const TRIM = 0.867
const PLATE = { rt: 1.45, pre: .014, bright: 9000, dark: 1800 }
const ROOM = { rt: .34, pre: .004, bright: 9000, dark: 3000 }
const tick = () => (globalThis.scheduler?.yield ? globalThis.scheduler.yield() : new Promise((r) => setTimeout(r, 0)))

// Data for the master at the usual device rate, made ahead of time in idle slices (prewarm) so the first tap only has the graph and two convolver loads left.
const warm = { sr: 0, job: null, data: null, done: false }
function* prepare(sr, into) {
  for (let c = 0; c < 2; c++) into.noise[c] = yield* noiseGen(sr, c)
  for (const [key, p] of [['room', ROOM], ['plate', PLATE]]) for (let c = 0; c < 2; c++) into[key][c] = yield* irGen(sr, p, c)
}
function warmStep(sr) {
  if (!warm.job || warm.sr !== sr) { warm.sr = sr; warm.data = { noise: [], plate: [], room: [] }; warm.job = prepare(sr, warm.data); warm.done = false }
  if (!warm.done && warm.job.next().done) warm.done = true
  return warm.done
}
/** Call from idle callbacks until it returns true: generates the noise and impulse responses for `sr` in slices, spending at most budgetMs per call. */
export function prewarm(sr = 48000, budgetMs = 8) {
  const t = performance.now()
  while (!warmStep(sr)) if (performance.now() - t >= budgetMs) return false
  return true
}

/**
 * createMaster for a phone: the same chain, built a slice at a time (whatever prewarm has not already made, the graph, two convolver loads) so the first tap
 * that unlocks audio never freezes the screen. Resolves when the chain is ready to play. trace(name, ms) reports how long each slice held the main thread.
 */
export async function createMasterAsync(ctx, { volume = 1, trace } = {}) {
  const sr = ctx.sampleRate
  let last = performance.now()
  const lap = async (name) => { const n = performance.now(); trace?.(name, n - last); await tick(); last = performance.now() }
  while (!warmStep(sr)) await lap('data')
  const assets = warm.data
  warm.job = null; warm.data = null; warm.done = false                       // the master owns it now (copied into audio buffers below); free the arrays
  await lap('data')
  const m = createMaster(ctx, { volume, assets, defer: true })
  await lap('graph')
  for (const [i, load] of m.finish.entries()) { load(); await lap(i ? 'plate convolver' : 'room convolver') }
  m.finish.length = 0
  return m
}

// ── voices ───────────────────────────────────────────────────────────────────────────────────────
// Glass partials: [ratio, amp, decay multiplier]. The 4.1 is the little inharmonic "ting"; partials above ~5 kHz are dropped.
const GLASS = [[2, .30, .55], [3, .10, .32], [4.1, .045, .10]]
const swells = new Map()
const swell = (skew) => {              // sin(π·u^skew): skew<1 peaks early, >1 builds to a late peak (risers)
  let c = swells.get(skew)
  if (!c) {
    c = new Float32Array(96)
    for (let i = 0; i < 96; i++) c[i] = Math.sin(Math.PI * (i / 95) ** skew)
    swells.set(skew, c)
  }
  return c
}

function voices(ctx, bus, t0, o = {}) {
  const rate = clamp(+o.rate || 1, .5, 2)
  const lite = !!o.lite                                  // data-fx="lite": no stereo-pair or 'ting' layers: a third fewer oscillators for the same tune
  const gpan = clamp(+o.pan || 0, -1, 1) * .8           // opts.pan shifts the whole cue's image (a dock tab on the left sounds on the left)
  const rnd = prng(((o.seed | 0) || 1) * 2654435761)
  const nz = noiseBuf(ctx)
  const T = (x) => t0 + x / rate

  const route = (node, pan = 0, send = 0) => {
    let n = node
    const pp = gpan ? clamp(pan * .5 + gpan, -1, 1) : pan
    if (pp) { const p = ctx.createStereoPanner(); p.pan.value = clamp(pp, -1, 1); n.connect(p); n = p }
    n.connect(bus.dry)
    if (send > 0) { const s = ctx.createGain(); s.gain.value = send; n.connect(s); s.connect(bus.send) }
  }
  /** a → hold → exponential release. Returns the time the voice is inaudible (-60 dB). ak > 1 bends the attack into a power curve (a swell that really builds). */
  const envelope = (g, t, peak, a, hold, tau, ak = 1) => {
    const p = g.gain
    p.setValueAtTime(0, t)
    if (ak > 1 && a > .05) {
      const c = new Float32Array(64)
      for (let i = 0; i < 64; i++) c[i] = peak * (i / 63) ** ak
      p.setValueCurveAtTime(c, t, a)
    } else p.linearRampToValueAtTime(peak, t + a)
    if (hold > 0) p.setValueAtTime(peak, t + a + hold)
    p.setTargetAtTime(0, t + a + hold, tau)
    return t + a + hold + tau * 7
  }

  /** The basic pitched voice. f/f2 Hz (glide f→f2 over `glide`), a attack, hold sustain, tau release constant. wide = ±cents stereo pair. */
  function tone(at, p) {
    const t = T(at), a = (p.a ?? .004) / rate, hold = (p.hold || 0) / rate, tau = (p.tau ?? .15) / rate
    const mix = ctx.createGain()
    const oscs = []
    const mk = (cents, pan, amp) => {
      const os = ctx.createOscillator(); os.type = p.type || 'sine'
      os.frequency.setValueAtTime(p.f * rate, t)
      if (p.f2) os.frequency.exponentialRampToValueAtTime(p.f2 * rate, t + (p.glide ?? .08) / rate)
      if (cents) os.detune.value = cents
      if (p.vib) {
        const l = ctx.createOscillator(), lg = ctx.createGain()
        l.frequency.value = p.vibHz ?? 5.5; lg.gain.value = p.vib; l.connect(lg); lg.connect(os.detune)
        oscs.push(l)
      }
      let out = os
      if (amp !== 1) { const ag = ctx.createGain(); ag.gain.value = amp; os.connect(ag); out = ag }
      if (pan) { const pn = ctx.createStereoPanner(); pn.pan.value = pan; out.connect(pn); pn.connect(mix) } else out.connect(mix)
      oscs.push(os)
    }
    // wide = ±cents: a centre voice plus a detuned pair panned out. Mono-safe — the beat is a slow breath (±2.5 dB), never a tremolo.
    if (p.wide && !lite) { mk(0, 0, 1); mk(-p.wide, -.8, .3); mk(p.wide, .8, .3); mix.gain.value = .8 } else { mk(0, 0, 1); if (p.wide) mix.gain.value = .87 }
    let node = mix
    if (p.lp) {
      const bq = ctx.createBiquadFilter(); bq.type = 'lowpass'; bq.Q.value = p.lpQ ?? .7
      bq.frequency.setValueAtTime(p.lp * rate, t)
      if (p.lpTo) bq.frequency.exponentialRampToValueAtTime(p.lpTo * rate, t + (p.lpT ?? .3) / rate)
      node.connect(bq); node = bq
    }
    const env = ctx.createGain(); node.connect(env)
    const end = envelope(env, t, p.gain ?? .2, a, hold, tau, p.ak)
    for (const os of oscs) { os.start(t); os.stop(end + .02) }
    route(env, p.pan, p.send ?? .2)
  }

  /** Filtered noise. With `tau`: a burst (click, spark, thock). Without: a swell shaped by `skew` over `dur` (whoosh, riser, rumble). */
  function noise(at, p) {
    const t = T(at), type = p.type || 'bandpass'
    const src = ctx.createBufferSource(); src.buffer = nz; src.loop = true
    const bq = ctx.createBiquadFilter(); bq.type = type; bq.Q.value = p.q ?? 1
    bq.frequency.setValueAtTime(p.f0 * rate, t)
    const env = ctx.createGain(); env.gain.value = 0
    src.connect(bq); bq.connect(env)
    let end
    if (p.tau) {
      end = envelope(env, t, p.gain ?? .2, .0012 / rate, 0, p.tau / rate)
      if (p.f1) bq.frequency.exponentialRampToValueAtTime(p.f1 * rate, t + 7 * p.tau / rate)
    } else {
      const d = p.dur / rate
      if (p.f1) bq.frequency.exponentialRampToValueAtTime(p.f1 * rate, t + d)
      const c = swell(p.skew ?? 1), peak = p.gain ?? .2, arr = new Float32Array(c.length)
      for (let i = 0; i < c.length; i++) arr[i] = c[i] * peak
      env.gain.setValueCurveAtTime(arr, t, d)
      end = t + d
    }
    src.start(t, rnd() * 1.4); src.stop(end + .03)
    route(env, p.pan, p.send ?? 0)
  }

  /** Glass strike: a bandpassed noise tick, optionally with a tiny pitched ping. */
  const tick = (at, p = {}) => {
    noise(at, { f0: p.f ?? 3200, q: p.q ?? 5, tau: p.tau ?? .004, gain: p.gain ?? .5, pan: p.pan, send: p.send ?? .06 })
    if (p.ping) tone(at, { f: p.ping, tau: p.pingTau ?? .03, gain: p.pingGain ?? .08, a: .001, pan: p.pan, send: p.send ?? .06 })
  }

  /** Soft low impact: a pitch-dropping tone plus a lowpassed noise body. Padded door, never a drum. type:'triangle' + lp gives it harmonics a phone speaker can reproduce. */
  const thump = (at, p = {}) => {
    const g = p.gain ?? .5
    tone(at, { f: p.f0 ?? 140, f2: p.f1 ?? 50, glide: p.pd ?? .05, tau: p.tau ?? .09, gain: g, a: p.a ?? .005, pan: p.pan, send: p.send ?? 0, type: p.type, lp: p.lp, lpTo: p.lpTo, lpT: p.lpT })
    if (p.body !== 0) noise(at, { f0: p.bodyF ?? 600, q: .7, type: 'lowpass', tau: .022, gain: g * (p.body ?? .3), pan: p.pan, send: p.send ?? 0 })
    if (p.tok) tone(at, { f: p.tokF ?? P(3), f2: (p.tokF ?? P(3)) * .66, glide: .03, tau: .024, gain: g * p.tok, a: .002, pan: p.pan, send: p.send ?? .05 })   // the knock: a short pitched tok where a phone speaker can reproduce it
  }

  /** Glass bell: FM strike that decays to a pure sine in ~100 ms, + octave/twelfth partials, + a detuned stereo pair, + a tick. */
  function bell(at, p) {
    const { f, gain = .2, tau = .4, send = .35, pan = 0, wide = 3, fm = 2.2, ratio = 2, strike = 1 } = p
    const t = T(at), fc = f * rate
    const car = ctx.createOscillator(), mod = ctx.createOscillator(), mg = ctx.createGain(), env = ctx.createGain()
    car.frequency.value = fc; mod.frequency.value = fc * ratio
    mg.gain.setValueAtTime(fc * ratio * fm, t)
    mg.gain.setTargetAtTime(fc * ratio * fm * .04, t, (p.fmTau ?? .03) / rate)
    mod.connect(mg); mg.connect(car.frequency); car.connect(env)
    const end = envelope(env, t, gain, .0015 / rate, 0, tau / rate)
    for (const os of [car, mod]) { os.start(t); os.stop(end + .02) }
    route(env, pan, send)
    for (const [r, amp, tm] of p.partials || GLASS) {
      if (f * r > 5200 || (lite && r > 3.5)) continue
      tone(at, { f: f * r, gain: gain * amp, tau: tau * tm, a: .0015, pan, send })
    }
    if (wide && !lite) {
      const k = 2 ** (wide / 1200)
      tone(at, { f: f * k, gain: gain * .36, tau, a: .002, pan: -.8, send })
      tone(at, { f: f / k, gain: gain * .36, tau, a: .002, pan: .8, send })
    }
    if (strike) tick(at, { f: clamp(f * 3.1, 2200, 4800), q: 4, gain: .22 * strike * (gain / .2), tau: .005, send: .1, pan })
  }

  /** Titanium bell: FM at an inharmonic ratio → metal, not glass. Shield, medal. */
  function metal(at, p) {
    const { f, gain = .2, tau = .5, send = .3, pan = 0, ratio = 1.4142, fm = 1.7 } = p
    const t = T(at), fc = f * rate
    const car = ctx.createOscillator(), mod = ctx.createOscillator(), mg = ctx.createGain(), env = ctx.createGain()
    car.frequency.value = fc; mod.frequency.value = fc * ratio
    mg.gain.setValueAtTime(fc * ratio * fm, t)
    mg.gain.setTargetAtTime(fc * ratio * fm * .12, t, tau / rate * .35)
    mod.connect(mg); mg.connect(car.frequency); car.connect(env)
    const end = envelope(env, t, gain, .001 / rate, 0, tau / rate)
    for (const os of [car, mod]) { os.start(t); os.stop(end + .02) }
    route(env, pan, send)
    tone(at, { f: f * 2, gain: gain * .22, tau: tau * .5, a: .001, pan, send })
    tick(at, { f: clamp(f * 2.6, 2400, 4600), q: 3, gain: .2 * (gain / .2), tau: .006, send: .08, pan })
  }

  /** Warm plucked tone: triangle through a closing lowpass. */
  const pluck = (at, p) => tone(at, { type: 'triangle', a: .002, tau: .26, lp: p.f * 7, lpTo: p.f * 1.6, lpT: .22, lpQ: 1.1, send: .3, ...p })
  /** Slow-attack pad: a wide sine plus a quiet 2nd harmonic. Sine, not triangle: no odd-harmonic honk around 400 Hz, yet the pitch still reads on a phone speaker. */
  const pad = (at, p) => {
    tone(at, { type: 'sine', a: .08, tau: .6, wide: 5, send: .35, ...p, lp: undefined })
    if (!lite) tone(at, { type: 'sine', a: .08, tau: .6, wide: 5, send: .35, ...p, f: p.f * 2, gain: (p.gain ?? .2) * .28, lp: undefined })
  }

  return { tone, noise, tick, thump, bell, metal, pluck, pad, rnd, step: clamp(o.step | 0, 0, 12), on: o.on !== false, final: !!o.final, tier: o.tier }
}

// ── the cues ─────────────────────────────────────────────────────────────────────────────────────
const CUE = {}
const def = (name, fn) => { CUE[name] = (ctx, bus, t0, opts) => fn(voices(ctx, bus, t0, opts)) }
const cents = (v, c = 10) => 2 ** (((v.rnd() - .5) * 2 * c) / 1200)   // humanise: ±c cents so repeated taps never machine-gun

// UI micro ·················································································
// Decay constants are exponential: a voice is 35 dB down after ~4 tau. Budgets live in CUE_META.
def('tap', (v) => {
  const j = cents(v)
  v.tick(0, { f: 2600, q: 3, gain: .55, tau: .006, send: .05 })
  v.thump(0, { f0: 190, f1: 125, pd: .02, tau: .018, gain: .15, body: 0 })
  v.tone(.001, { f: P(8) * j, tau: .02, gain: .09, a: .001, send: .1 })
})
def('select', (v) => {
  const j = cents(v)
  v.tick(0, { f: 3400, q: 4, gain: .6, tau: .006, send: .08 })
  v.thump(0, { f0: 230, f1: 150, pd: .02, tau: .022, gain: .17, body: 0 })
  v.tone(.001, { f: P(7) * j, tau: .036, gain: .16, a: .001, send: .2 })
  v.tone(.001, { f: P(10) * j, tau: .02, gain: .05, a: .001, send: .2 })
})
def('deselect', (v) => {
  const j = cents(v)
  v.tick(0, { f: 1900, q: 2.5, gain: .4, tau: .006, send: .05 })
  v.tone(.001, { f: P(3) * j, f2: P(2) * j, glide: .06, tau: .03, gain: .13, a: .002, send: .15 })
})
def('toggle', (v) => {
  v.thump(0, { f0: 175, f1: 110, pd: .02, tau: .02, gain: .2, body: .2 })
  v.tick(0, { f: 2200, q: 3, gain: .45, tau: .005 })
  const a = v.on ? [P(6), P(8)] : [P(8), P(6)]            // up when switched on, down when off
  v.tick(.036, { f: 3600, q: 4, gain: .35, tau: .005, send: .08 })
  v.tone(.036, { f: a[0], f2: a[1], glide: .04, tau: .042, gain: .15, a: .001, send: .22 })
})
def('detent', (v) => {                                     // one click of a slider or picker wheel; opts.step (0-9) climbs D5 to B6 so a drag reads as a rising scale
  const d = 5 + Math.min(v.step, 9)
  v.tick(0, { f: 4200, q: 5, gain: .45, tau: .0035, send: .03 })
  v.tone(0, { f: P(d), tau: .016, gain: .1, a: .001, send: .06 })
})
def('nav', (v) => {
  const j = cents(v, 6)
  v.noise(0, { dur: .1, f0: 900, f1: 2300, q: 1.2, gain: .075, skew: 1, send: .1 })
  v.tone(.03, { f: P(6) * j, tau: .045, gain: .13, a: .002, send: .22 })
  v.tick(.03, { f: 3000, q: 4, gain: .25, tau: .004 })
})
def('open', (v) => {
  v.noise(0, { dur: .2, f0: 420, f1: 2600, q: 1, gain: .1, skew: 1.7, send: .12 })
  v.tone(.1, { f: P(5), tau: .05, gain: .12, a: .002, send: .3 })
  v.tone(.15, { f: P(8), tau: .07, gain: .1, a: .002, send: .35 })
})
def('close', (v) => {
  v.noise(0, { dur: .15, f0: 2200, f1: 520, q: 1, gain: .085, skew: .7, send: .1 })
  v.thump(.12, { type: 'triangle', f0: 247, f1: 147, pd: .04, tau: .05, gain: .3, lp: 1600, lpTo: 500, lpT: .07, body: .45, bodyF: 800, tok: .7, tokF: P(3) })       // the door seating
  v.tone(.12, { f: P(3), tau: .05, gain: .07, a: .002, send: .25 })
})
def('next', (v) => {
  v.tick(0, { f: 3000, q: 3, gain: .35, tau: .005 })
  v.tone(0, { f: P(5), f2: P(6), glide: .03, tau: .055, gain: .15, a: .002, send: .25 })
  v.tone(0, { f: P(11), tau: .03, gain: .03, a: .002, send: .3 })
})
def('check', (v) => {
  v.tick(0, { f: 2400, q: 3, gain: .5, tau: .006, send: .05 })
  v.tone(0, { f: P(3), f2: P(5), glide: .08, tau: .06, gain: .14, a: .003, send: .22 })
  v.tone(0, { f: P(-5), tau: .06, gain: .16, a: .003, send: 0 })
})

// Verdicts ·················································································
def('correct', (v) => {                                    // F# → A: a rising glass chime that resolves up
  v.bell(0,    { f: P(7), gain: .26, tau: .19, send: .38, pan: -.12 })
  v.bell(MARKS.correct.resolve, { f: P(8), gain: .30, tau: .24, send: .42, pan: .12 })
  v.tone(MARKS.correct.resolve, { f: P(0), tau: .16, gain: .12, a: .004, send: .2 })      // D4 under it: the chord is D–F#–A
  v.tone(.13, { f: P(15), tau: .08, gain: .03, a: .002, send: .5 })
})
def('wrong', (v) => {                                      // soft low double-thud, never a buzzer. Triangle + lowpass: the fundamentals sit low (B3→D3, F#3→A2) but the harmonics reach a phone speaker.
  v.thump(0,    { type: 'triangle', f0: 247, f1: 147, pd: .05, tau: .06, gain: .4, lp: 1600, lpTo: 500, lpT: .08, body: .5, bodyF: 1000, tok: 1.2, tokF: P(4), send: .06 })
  v.thump(.118, { type: 'triangle', f0: 185, f1: 110, pd: .05, tau: .075, gain: .32, lp: 1400, lpTo: 450, lpT: .09, body: .45, bodyF: 900, tok: 1.1, tokF: P(2), send: .06 })
  v.tone(0, { f: 110, f2: 92, glide: .2, tau: .1, gain: .07, a: .005, send: 0 })                           // the weight, for headphones
})
def('combo', (v) => {                                      // a rising triad that climbs the scale with `step`
  const s = Math.min(v.step, 3)
  ;[5, 7, 8].forEach((d, i) => v.pluck(i * .055, { f: P(d + s), gain: .13, tau: .11, send: .35 }))
  v.bell(MARKS.combo.top, { f: P(10 + s), gain: .22, tau: .2, send: .42 })
})
def('xp', (v) => {
  const f = P(9 + Math.min(v.step, 4))
  v.tone(0, { f, tau: .04, gain: .13, a: .001, send: .3 })
  v.tone(0, { f: f * 2, tau: .022, gain: .03, a: .001, send: .3 })
  v.tick(0, { f: 4200, q: 4, gain: .22, tau: .004 })
})
def('error', (v) => {                                      // muted, descending, apologetic — not a buzzer, not a thud
  v.pluck(0,    { f: P(2), gain: .2, tau: .08, lp: 1500, lpTo: 400, lpT: .1, send: .12 })
  v.pluck(.105, { f: P(0), gain: .2, tau: .1, lp: 1300, lpTo: 330, lpT: .14, send: .12 })
  v.thump(.105, { f0: 230, f1: 130, pd: .05, tau: .06, gain: .18, body: .3, bodyF: 800 })
})
def('countdown', (v) => {
  if (v.final) {                                           // zero: the fifth
    v.bell(0, { f: P(5), gain: .24, tau: .1, send: .3, strike: .6 })
    v.bell(0, { f: P(8), gain: .22, tau: .13, send: .34, strike: 0 })
  } else {
    v.tone(0, { f: P(3), tau: .055, gain: .2, a: .002, send: .22 })
    v.tick(0, { f: 3000, q: 4, gain: .3, tau: .005 })
  }
})
def('go', (v) => {                                         // mission control: "go". Two clean notes a fifth apart.
  v.noise(0, { dur: .12, f0: 1800, f1: 3600, q: 1.2, gain: .05, skew: .8, send: .1 })
  v.bell(.015, { f: P(5), gain: .26, tau: .09, send: .32 })
  v.bell(MARKS.go.go, { f: P(8), gain: .3, tau: .2, send: .42 })
  v.tone(MARKS.go.go, { f: P(12), tau: .07, gain: .03, a: .002, send: .5 })
  v.thump(.0, { f0: 150, f1: 90, pd: .03, tau: .05, gain: .16, body: 0 })
})
def('ring', (v) => {                                       // a progress ring closing; step 0/1/2 → D / F# / A
  const base = 5 + [0, 2, 3, 5][Math.min(v.step, 3)]
  v.tone(0, { f: P(base - 3), f2: P(base), glide: .2, a: .05, hold: .04, tau: .05, gain: .06, send: .25 })
  v.bell(MARKS.ring.close, { f: P(base), gain: .27, tau: .22, send: .42 })
  v.bell(MARKS.ring.close, { f: P(base + 5), gain: .08, tau: .16, send: .5, strike: 0 })
})

// Rewards ··································································································
def('streak', (v) => {                                     // the flame catches: a low "fwump", then a rising fifth
  v.noise(0, { dur: .34, f0: 260, f1: 1500, q: .9, gain: .2, skew: 1.2, send: .18 })
  v.thump(0, { f0: 112, f1: 55, pd: .1, tau: .12, gain: .32, body: .3, send: .05 })
  v.pad(.03, { f: P(-5), gain: .1, a: .09, hold: .1, tau: .22, lp: 900 })
  v.pad(.03, { f: P(-2), gain: .08, a: .09, hold: .1, tau: .22, lp: 1100 })
  v.bell(MARKS.streak.catch, { f: P(5), gain: .22, tau: .2, send: .4 })
  v.bell(.25, { f: P(8), gain: .24, tau: .24, send: .44 })
  v.bell(.39, { f: P(10), gain: .22, tau: .3, send: .5 })
  v.tone(.5, { f: P(13), tau: .14, gain: .03, a: .002, send: .5 })
})
def('shield', (v) => {                                     // a plate locking into place, then a field hum
  v.thump(0, { f0: 150, f1: 58, pd: .07, tau: .1, gain: .42, body: .5, send: .05 })
  v.metal(.015, { f: P(4), gain: .2, tau: .26, send: .3, pan: -.1 })
  v.metal(.05, { f: P(7), gain: .2, tau: .28, send: .34, pan: .1 })
  v.tone(.2, { f: P(4), a: .14, hold: .06, tau: .16, gain: .05, vib: 9, vibHz: 6, send: .4 })
  v.bell(.3, { f: P(10), gain: .13, tau: .22, send: .45, strike: .4 })
})
def('chest', (v) => {                                      // latch, lid, a cascade of harp notes, a resolving bell
  v.tick(0, { f: 1700, q: 2, gain: .5, tau: .008 })
  v.thump(0, { f0: 210, f1: 120, pd: .02, tau: .03, gain: .24, body: .3 })
  v.tick(.05, { f: 3100, q: 3, gain: .5, tau: .006 })
  v.noise(.1, { dur: .34, f0: 420, f1: 3000, q: 1, gain: .09, skew: 1.5, send: .2 })
  ;[5, 7, 8, 9, 10, 12].forEach((d, i) => v.pluck(MARKS.chest.burst + i * .055, { f: P(d), gain: .13, tau: .14, send: .4, lp: P(d) * 6, lpTo: P(d) * 1.4 }))
  v.bell(MARKS.chest.chime, { f: P(8), gain: .2, tau: .24, send: .5 })
  v.bell(MARKS.chest.chime, { f: P(10), gain: .22, tau: .32, send: .5 })
  v.pad(MARKS.chest.burst, { f: P(-5), gain: .09, a: .2, hold: .1, tau: .25, lp: 900 })
})
def('reveal', (v) => {                                     // a card flips: slide, snap, glass
  v.noise(0, { dur: .13, f0: 700, f1: 2600, q: 1.1, gain: .1, skew: .9, send: .1 })
  v.tick(MARKS.reveal.flip, { f: 2800, q: 3, gain: .5, tau: .006 })
  v.thump(MARKS.reveal.flip, { f0: 190, f1: 110, pd: .03, tau: .03, gain: .2, body: .2 })
  v.bell(MARKS.reveal.flip + .04, { f: P(10), gain: .24, tau: .22, send: .45 })
  v.bell(.27, { f: P(13), gain: .1, tau: .2, send: .5, strike: .3 })
  v.tone(MARKS.reveal.flip + .04, { f: P(5), tau: .16, gain: .1, a: .004, send: .3 })
})
def('rare', (v) => {                                       // gold: a two-octave pentatonic run into a held, shimmering chord
  ;[5, 6, 7, 8, 9, 10, 11, 12, 13].forEach((d, i) => v.bell(i * .052, { f: P(d), gain: .1 + i * .005, tau: .1 + i * .008, send: .42, wide: 5, strike: .5 }))
  const t = MARKS.rare.chord
  v.bell(t, { f: P(10), gain: .22, tau: .42, send: .5, wide: 7 })
  v.bell(t, { f: P(13), gain: .17, tau: .46, send: .55, wide: 7, strike: 0 })
  v.bell(t + .02, { f: P(15), gain: .1, tau: .38, send: .55, wide: 7, strike: 0 })
  v.pad(t - .1, { f: P(0), gain: .1, a: .2, hold: .3, tau: .3, lp: 1400 })
  v.pad(t - .1, { f: P(3), gain: .08, a: .2, hold: .3, tau: .3, lp: 1600 })
  ;[16, 15, 13, 12, 11].forEach((d, i) => v.tone(.85 + i * .11, { f: P(d), tau: .14, gain: .03, a: .002, send: .6, wide: 8 }))
})
def('unlock', (v) => {                                     // a lock releasing: two clicks, a spring, an ascending bell
  v.tick(0, { f: 2100, q: 3, gain: .55, tau: .006 })
  v.thump(0, { f0: 200, f1: 115, pd: .02, tau: .028, gain: .22, body: .2 })
  v.tick(.045, { f: 3300, q: 4, gain: .45, tau: .005 })
  v.tone(.06, { f: P(8), f2: P(10), glide: .05, tau: .03, gain: .04, a: .001, send: .3 })
  v.bell(MARKS.unlock.release, { f: P(3), gain: .22, tau: .14, send: .4 })
  v.bell(.19, { f: P(5), gain: .26, tau: .2, send: .46 })
})
def('medal', (v) => {                                     // titanium: two struck metal bells and a short shimmer. opts.tier: bronze (low, plain) · silver · gold (longer shimmer, a held fifth) · ti (default)
  const [d0, d1, n] = { bronze: [7, 10, 0], silver: [8, 12, 2], gold: [10, 13, 4] }[v.tier] || [10, 13, 3]
  const g = v.tier === 'bronze' ? .85 : 1
  v.thump(0, { f0: 170, f1: 85, pd: .04, tau: .06, gain: .26 * g, body: .3 })
  v.metal(0, { f: P(d0), gain: .24 * g, tau: .3, send: .38, pan: -.15 })
  v.metal(.07, { f: P(d1), gain: .21 * g, tau: .34, send: .42, pan: .15 })
  ;[12, 13, 15, 17].slice(0, n).forEach((d, i) => v.bell(.24 + i * .06, { f: P(d), gain: .08, tau: .16, send: .5, strike: .3 }))
  v.pad(.05, { f: P(0), gain: .07, a: .1, hold: .1, tau: .2, lp: 1000 })
  if (v.tier === 'gold') v.pad(.1, { f: P(3), gain: .06, a: .12, hold: .2, tau: .3, lp: 1200 })
})

// Hero moments ·····························································································
def('ignite', (v) => {                                     // the start button: a deliberate decision, then the turbine spools
  v.thump(0, { f0: 100, f1: 42, pd: .12, tau: .14, gain: .38, body: .5, send: .05 })
  v.thump(0, { f0: 300, f1: 147, pd: .06, tau: .08, gain: .3, body: .4, bodyF: 800, tok: .7, tokF: P(3), send: .05 })       // the clunk a phone can hear
  v.tick(0, { f: 1800, q: 2, gain: .6, tau: .008 })
  v.tick(.025, { f: 3200, q: 3, gain: .5, tau: .006 })
  v.noise(.03, { f0: 2800, f1: 900, q: .8, tau: .05, gain: .16, send: .1 })
  v.tone(.06, { f: P(-5), f2: P(0), glide: .26, type: 'triangle', a: .02, tau: .08, gain: .15, lp: 600, lpTo: 2200, lpT: .26, send: .15 })
  v.bell(.3, { f: P(5), gain: .13, tau: .13, send: .4, strike: .4 })
})
def('launch', (v) => {                                     // ~2.5 s: ignition → engine swell + a climbing whine → rising ladder → lift on D
  v.thump(0, { f0: 130, f1: 48, pd: .12, tau: .09, gain: .22, body: .6, bodyF: 500, send: .05 })         // a short cough; the swell is the point
  ;[[0, 2400], [.03, 1800], [.07, 3000], [.11, 2100], [.16, 2700]].forEach(([t, f]) => v.tick(t, { f, q: 2, gain: .22, tau: .012, send: .1 }))
  // The engine is a stack of sines (no triangle honk) on a power-curve swell: it builds, it does not start at full. D1 is felt, D2-D4 carry it.
  v.tone(0, { f: P(-15), a: 1.85, ak: 2.4, hold: .15, tau: .16, gain: .12, send: 0 })
  v.tone(0, { f: P(-10), a: 1.8, ak: 2.4, hold: .15, tau: .16, gain: .15, send: .05 })
  v.tone(0, { f: P(-5), a: 1.8, ak: 2.4, hold: .15, tau: .16, gain: .16, send: .1, wide: 3 })
  v.tone(.1, { f: P(-2), a: 1.75, ak: 2.4, hold: .1, tau: .16, gain: .08, send: .12, wide: 4 })
  v.tone(.15, { f: P(0), a: 1.7, ak: 2.4, hold: .1, tau: .16, gain: .07, send: .15, wide: 4 })
  v.noise(0, { dur: 2.5, f0: 120, f1: 700, type: 'lowpass', q: .7, gain: .3, skew: 2.2 })                                                  // rumble
  v.tone(.05, { f: P(-5), f2: P(5), glide: 1.88, a: 1.2, ak: 2, hold: .6, tau: .05, gain: .06, vib: 6, vibHz: 5.5, send: .3 })            // the spool-up whine, D3 → D5
  v.noise(.1, { dur: 2.2, f0: 350, f1: 3400, q: .9, gain: .4, skew: 3, send: .15, pan: -.3 })                                              // wash, left and right
  v.noise(.1, { dur: 2.2, f0: 420, f1: 3000, q: .9, gain: .4, skew: 3, send: .15, pan: .3 })
  ;[[.28, -5], [.56, -2], [.82, 0], [1.05, 2], [1.26, 3], [1.45, 4], [1.62, 5], [1.77, 7]].forEach(([t, d], i) => {
    if (d < 3) v.pluck(t, { f: P(d), gain: .11 + i * .012, tau: .2, send: .3 })
    else v.bell(t, { f: P(d), gain: .1 + i * .01, tau: .16, send: .38, strike: .5 })
  })
  const lift = MARKS.launch.lift
  v.thump(lift, { f0: 150, f1: 55, pd: .1, tau: .16, gain: .22, body: .35, bodyF: 600, send: .1 })
  v.bell(lift, { f: P(5), gain: .26, tau: .24, send: .45, wide: 4 })
  v.bell(lift, { f: P(8), gain: .22, tau: .25, send: .48, wide: 4, strike: .3 })
  v.bell(lift + .04, { f: P(10), gain: .2, tau: .27, send: .52, wide: 5, strike: .3 })
  v.pad(lift, { f: P(0), gain: .09, a: .05, hold: .05, tau: .16 })
})
def('complete', (v) => {                                   // ~2.8 s: five stacked fifths D A E B F#, a melody over them, a falling shimmer
  v.thump(0, { f0: 120, f1: 45, pd: .18, tau: .2, gain: .28, body: .45, bodyF: 600, send: .08 })
  v.noise(0, { dur: .6, f0: 500, f1: 2600, q: .8, gain: .13, skew: 2.4, send: .2 })
  ;[-5, -2, 1, 4, 7].forEach((d, i) => {                  // D3 A3 E4 B4 F#5
    const t = .1 + i * .15
    v.pad(t, { f: P(d), gain: .08 - i * .006, a: .07, hold: .9 - i * .12, tau: .3, send: .38 })
    v.bell(t, { f: P(d + 5), gain: .17, tau: .3, send: .42, wide: 4 })
  })
  v.tone(.5, { f: P(-10), a: .5, ak: 1.8, hold: .5, tau: .2, gain: .12, send: .05 })                 // D2 bloom
  v.bell(.85, { f: P(8), gain: .22, tau: .34, send: .48, wide: 5 })
  v.bell(MARKS.complete.hit, { f: P(10), gain: .28, tau: .5, send: .52, wide: 6 })
  v.bell(MARKS.complete.hit, { f: P(15), gain: .06, tau: .4, send: .55, wide: 6, strike: 0 })
  ;[15, 13, 12, 10, 9, 8].forEach((d, i) => v.bell(1.3 + i * .13, { f: P(d), gain: .07 - i * .005, tau: .2, send: .55, wide: 6, strike: .2 }))
})
def('rankup', (v) => {                                     // a fast ladder of plucks into an impact on a wide chord
  ;[0, 1, 2, 3, 4, 5].forEach((d, i) => {
    if (i < 4) v.pluck(i * .075, { f: P(d), gain: .15 + i * .015, tau: .14, send: .3 })
    else v.bell(i * .075, { f: P(d), gain: .16 + i * .02, tau: .16, send: .4, strike: .5 })
  })
  v.noise(0, { dur: .5, f0: 300, f1: 2400, q: .8, gain: .12, skew: 2.2, send: .15 })
  const t = MARKS.rankup.impact
  v.thump(t, { f0: 150, f1: 50, pd: .14, tau: .2, gain: .4, body: .5, bodyF: 600, send: .08 })
  v.tone(t, { f: P(-10), a: .02, hold: .2, tau: .2, gain: .12, send: .05 })
  v.bell(t, { f: P(5), gain: .24, tau: .4, send: .48, wide: 5 })
  v.bell(t, { f: P(8), gain: .22, tau: .4, send: .5, wide: 5, strike: .3 })
  v.bell(t, { f: P(10), gain: .22, tau: .45, send: .52, wide: 6, strike: .3 })
  v.bell(t + .03, { f: P(12), gain: .12, tau: .36, send: .55, wide: 6, strike: 0 })
  v.pad(t, { f: P(-5), gain: .09, a: .03, hold: .25, tau: .26 })
  v.pad(t, { f: P(2), gain: .07, a: .03, hold: .25, tau: .26 })
  ;[15, 13, 12, 10].forEach((d, i) => v.bell(.9 + i * .11, { f: P(d), gain: .06, tau: .18, send: .55, wide: 6, strike: .2 }))
})
def('splash', (v) => {                                     // ignition: ratchet of ticks, needle glide to redline and back, a warm D2, an ember
  const S = MARKS.splash
  let t = 0, gap = .085, k = 0
  while (t < S.redline) {
    const d = -2 + Math.floor(k * .66)
    v.tick(t, { f: 2600 + k * 70, q: 6, gain: .4 + k * .02, tau: .005, send: .1, pan: ((k % 2) * 2 - 1) * .25 })
    v.tone(t, { f: P(Math.min(d, 10)), tau: .04, gain: .05 + k * .003, a: .001, send: .25 })
    t += gap; gap = Math.max(.024, gap * .93); k++
  }
  v.tone(0, { f: P(-2), f2: P(10), glide: S.redline, a: .3, hold: .55, tau: .04, gain: .08, send: .3 })                              // needle up
  v.tone(S.redline, { f: P(10), f2: P(5), glide: .34, a: .01, hold: .0, tau: .2, gain: .06, send: .35 })                              // and back to rest
  v.tone(0, { f: P(-10), a: .8, ak: 1.8, hold: .1, tau: .16, gain: .2, send: .06 })                                            // warm D2: sines, never a honk
  v.tone(0, { f: P(-5), a: .85, ak: 1.8, hold: .1, tau: .18, gain: .14, send: .1, wide: 3 })
  v.tone(.5, { f: P(-2), a: .5, hold: .1, tau: .16, gain: .05, send: .2, wide: 4 })
  v.noise(S.wordmark, { dur: .55, f0: 1400, f1: 2600, q: 1.5, gain: .06, skew: 1.2, send: .15 })                                      // the wordmark tracking in
  v.tick(S.ember - .02, { f: 2200, q: 2, gain: .5, tau: .01 }); v.tick(S.ember + .005, { f: 3400, q: 3, gain: .45, tau: .008 })    // ember
  v.bell(S.ember, { f: P(10), gain: .26, tau: .3, send: .5, wide: 4 })
  v.bell(S.ember + .08, { f: P(12), gain: .11, tau: .24, send: .55, strike: .2 })
})
export const CUE_FNS = CUE
export const CUE_NAMES = Object.keys(CUE)

/**
 * kind    ui (micro: tight room reverb) · reward (a verdict or a gift: plate) · hero (long, plate, ducks everything else)
 * body    seconds until the cue is 35 dB below its own peak — what the ear takes as "the sound". The audit fails a cue that outstays it.
 * len     seconds until the very last ring-out is below -60 dBFS (reverb included) — cleanup + the audit's tail check
 * pitched has a tonal centre (the audit checks it sits on the D-pentatonic)
 * lufs    loudness the cue is mixed to at volume 1: K-weighted over its active region (ui, reward) or its loudest 400 ms (hero, which build and release). The audit warns when a cue drifts > 3 LU, so a tweak cannot quietly unbalance the set
 * level   this cue's own trim (linear), applied in cueBus() live and offline
 * duck    { depth, ms }: how far everything else drops while this plays
 */
export const CUE_META = {
  tap:       { kind: 'ui',     body: 0.14, len: .9,  level: 2.19, pitched: true,  lufs: -24, label: 'Tap',       note: 'every press: a damped titanium switch + a pip' },
  select:    { kind: 'ui',     body: 0.22,  len: .9,  level: 1.79, pitched: true,  lufs: -23, label: 'Select',    note: 'choosing an answer plate: F# glass tick' },
  deselect:  { kind: 'ui',     body: 0.2, len: .9,  level: 2.39, pitched: true,  lufs: -25, label: 'Deselect',  note: 'the inverse: a softer, falling A to F#' },
  toggle:    { kind: 'ui',     body: 0.3,  len: .9,  level: 1.71, pitched: true,  lufs: -23, label: 'Toggle',    note: 'relay click; the pip rises on, falls off (opts.on)' },
  detent:    { kind: 'ui',     body: 0.12, len: .6, level: 2.8, pitched: true,  lufs: -27, label: 'Detent',    note: 'slider / picker click; opts.step climbs the scale' },
  nav:       { kind: 'ui',     body: 0.3,  len: .9,  level: 1.95, pitched: true,  lufs: -24, label: 'Nav',       note: 'dock tab: air + E5' },
  open:      { kind: 'ui',     body: 0.5, len: 1.1, level: 1.62, pitched: true,  lufs: -23, label: 'Open',      note: 'sheet rises: whisper sweep, D5 to A5' },
  close:     { kind: 'ui',     body: 0.4,  len: 1.0, level: 0.89, pitched: true,  lufs: -22, label: 'Close',     note: 'sheet falls, then the door seats' },
  next:      { kind: 'ui',     body: 0.35,  len: .9,  level: 2.05, pitched: true,  lufs: -24, label: 'Next',      note: 'slide advance: D5 to E5 tick' },
  check:     { kind: 'ui',     body: 0.35, len: .9,  level: 1.94, pitched: true,  lufs: -22, label: 'Check',     note: 'arming: A4 to D5 with a D3 body' },
  correct:   { kind: 'reward', body: 1.05,  len: 2.6, level: 1.03, pitched: true,  lufs: -18, label: 'Correct',   note: 'F#5 to A5 rising glass chime over D4' },
  wrong:     { kind: 'reward', body: 0.55, len: 1.4, level: 0.89, pitched: false, lufs: -20, label: 'Wrong',     note: 'soft low double-thud (never a buzzer)' },
  combo:     { kind: 'reward', body: 1.1, len: 2.4, level: 1.3, pitched: true,  lufs: -18, label: 'Combo',     note: 'rising triad; opts.step climbs the scale' },
  xp:        { kind: 'ui',     body: .26, len: .9,  level: 2.44, pitched: true,  lufs: -24, label: 'XP',        note: 'a counting tick; opts.step climbs' },
  streak:    { kind: 'reward', body: 1.7, len: 3.2, level: 1, pitched: true,  lufs: -17, label: 'Streak',    note: 'the flame catches: fwump + rising fifth' },
  shield:    { kind: 'reward', body: 1.5, len: 3.0, level: 1.38, pitched: true,  lufs: -18, label: 'Shield',    note: 'plate locks; titanium bells; field hum' },
  chest:     { kind: 'reward', body: 2.1, len: 3.2, level: 1.11, pitched: true,  lufs: -17, label: 'Chest',     note: 'latch, lid, harp cascade, resolve' },
  reveal:    { kind: 'reward', body: 1.15, len: 2.8, level: 1.1, pitched: true,  lufs: -18, label: 'Reveal',    note: 'card flip: slide, snap, glass D6' },
  rare:      { kind: 'reward', body: 2.6, len: 3.8, level: 1.04, pitched: true,  lufs: -16, label: 'Rare',      note: 'gold: two-octave run into a shimmering chord' },
  unlock:    { kind: 'reward', body: 1.0,  len: 2.4, level: 0.92, pitched: true,  lufs: -19, label: 'Unlock',    note: 'lock releases; A4 to D5 bells' },
  ignite:    { kind: 'reward', body: .95,  len: 2.0, level: 1.78, pitched: true,  lufs: -17, label: 'Ignite',    note: 'the start button: the decision' },
  launch:    { kind: 'hero',   body: 3.0, len: 4.6, level: 0.67, pitched: true,  lufs: -14, label: 'Launch',    note: '2.5 s ignition swell, lift on D', duck: { depth: .35, ms: 2600 } },
  complete:  { kind: 'hero',   body: 3.1, len: 4.8, level: 0.73, pitched: true,  lufs: -14, label: 'Complete',  note: '2.8 s fanfare: D A E B F# stacked fifths', duck: { depth: .3, ms: 3000 } },
  rankup:    { kind: 'hero',   body: 2.5, len: 4.2, level: 0.52, pitched: true,  lufs: -14, label: 'Rank up',   note: 'ladder into impact on a wide chord', duck: { depth: .35, ms: 2200 } },
  medal:     { kind: 'reward', body: 1.6, len: 3.2, level: 1.13, pitched: true,  lufs: -18, label: 'Medal',     note: 'two struck titanium bells + shimmer' },
  error:     { kind: 'ui',     body: 0.6, len: 1.2, level: 1.15, pitched: true,  lufs: -21, label: 'Error',     note: 'muted descending F# to D, apologetic' },
  countdown: { kind: 'ui',     body: 0.35, len: 1.0, level: 2.1, pitched: true,  lufs: -22, label: 'Countdown', note: 'T-minus pip A4; opts.final = the fifth' },
  go:        { kind: 'reward', body: 0.95,  len: 2.4, level: 0.95, pitched: true,  lufs: -18, label: 'Go',        note: 'mission-control go: D5 to A5' },
  ring:      { kind: 'reward', body: 1.15, len: 2.4, level: 1.37, pitched: true,  lufs: -19, label: 'Ring',      note: 'a ring closes; opts.step 0/1/2 gives D/F#/A' },
  splash:    { kind: 'hero',   body: 2.3, len: 4.0, level: 0.81, pitched: true,  lufs: -15, label: 'Splash',    note: 'ratchet, needle glide to redline, warm D2, ember', duck: { depth: .5, ms: 1500 } },
}

/** The bus a cue plays on: kind picks the reverb + duck behaviour, meta.level is the cue's own trim. Live and offline both use this. */
export const cueBus = (master, cue, gain = 1) => master.bus(gain * (CUE_META[cue].level ?? 1), CUE_META[cue].kind)

/**
 * One cue, scheduled on a master: its bus, its notes, and the duck it causes. The live engine and every offline render use this one function,
 * so what the audit measures is what the phone plays. Returns { bus, end, busy } in context time: `end` the reverb is out, `busy` the body is over.
 */
export function schedule(ctx, master, cue, at, opts = {}) {
  const meta = CUE_META[cue]
  if (!meta) throw new Error('unknown cue: ' + cue)
  const rate = clamp(+opts.rate || 1, .5, 2)
  const bus = cueBus(master, cue, clamp(opts.gain ?? 1, 0, 2))
  try { CUE[cue](ctx, bus, at, opts) } catch (e) { bus.dispose(); throw e }
  if (meta.duck) master.duck(meta.duck.depth, meta.duck.ms / 1000 / rate, at)
  return { bus, end: at + meta.len / rate, busy: at + meta.body / rate }
}

/**
 * Render one cue through the *real* master chain with an OfflineAudioContext → AudioBuffer (stereo).
 * volume defaults to 1: the reference level the cues are designed and measured at.  prepare(ctx) runs first (the audit counts nodes there).
 */
export async function renderCue(cue, { sampleRate = 48000, volume = 1, tail = 1.2, prepare, ...opts } = {}) {
  const meta = CUE_META[cue]
  if (!meta) throw new Error('unknown cue: ' + cue)
  const rate = clamp(+opts.rate || 1, .5, 2)
  const secs = meta.len / rate + tail + .02
  const ctx = new OfflineAudioContext(2, Math.ceil(secs * sampleRate), sampleRate)
  prepare?.(ctx)
  const master = createMaster(ctx, { volume })
  schedule(ctx, master, cue, .02, { seed: 1, ...opts })
  return ctx.startRendering()
}

/** Render a sequence: steps = [[cue, atMs, opts?], …], the way a screen would fire them (ducks and all). */
export async function renderSequence(steps, { sampleRate = 48000, volume = 1, tail = 1.2, prepare, ...base } = {}) {
  let end = 0
  for (const [cue, ms, o] of steps) {
    const meta = CUE_META[cue]
    if (!meta) throw new Error('unknown cue: ' + cue)
    end = Math.max(end, ms / 1000 + meta.len / clamp(+o?.rate || 1, .5, 2))
  }
  const ctx = new OfflineAudioContext(2, Math.ceil((end + tail + .02) * sampleRate), sampleRate)
  prepare?.(ctx)
  const master = createMaster(ctx, { volume })
  let seed = 1
  for (const [cue, ms, o] of steps) schedule(ctx, master, cue, .02 + ms / 1000, { ...base, ...o, seed: seed++ })
  return ctx.startRendering()
}
