#!/usr/bin/env python3
"""
Voice generation for The Stewardship Code animated series.

Two engines, on purpose (see 00-SERIES-BIBLE.md):

  NARRATOR  -> ElevenLabs, generated by hand in the web app and dropped in as
               narr-<ep>-<id>.mp3. ~3000 credits total for the series means the
               teaching voice gets the premium engine and nothing else does.
  CHARACTERS -> edge-tts, free and unlimited, Nigerian and Kenyan neural voices
               pitched toward the character's age.

This script owns the edge-tts half and the assembly of both halves into per-episode
stems. It is deliberately idempotent: lines already rendered are skipped, so a re-run
after a script tweak only costs the changed lines.

    python cast.py ep1              # render episode 1 dialogue
    python cast.py ep1 --force      # re-render even if files exist
    python cast.py ep1 --report     # character counts + durations, generate nothing

Pitch note: no neural voice sounds like a 15-year-old. Abeo and Ezinne are adult
Nigerian voices lifted a few semitones, which is close enough to cut picture against
and still reads adult to a teenager. Treat Micah and Ada as replaceable.
"""
from __future__ import annotations

import asyncio
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# --------------------------------------------------------------------------------------
# Casting. Rate/pitch are edge-tts prosody strings.
# --------------------------------------------------------------------------------------
CAST = {
    # Nigerian male, lifted toward a teenager. The weakest voice in the series.
    "MICAH":  {"voice": "en-NG-AbeoNeural",     "rate": "+6%",  "pitch": "+18Hz"},
    # Nigerian female, lifted slightly. Holds up best of the three.
    "ADA":    {"voice": "en-NG-EzinneNeural",   "rate": "+4%",  "pitch": "+12Hz"},
    # Kenyan male, slowed and dropped. Older, unhurried, asks rather than tells.
    "OKAFOR": {"voice": "en-KE-ChilembaNeural", "rate": "-6%",  "pitch": "-12Hz"},
}

# NARRATOR is not here on purpose — it is not generated by this script.
ELEVENLABS_VOICE = "Adeola - Conversational African Female"


def load(ep: str) -> dict:
    path = HERE / f"{ep}-lines.json"
    if not path.exists():
        sys.exit(f"no line sheet at {path}")
    return json.loads(path.read_text(encoding="utf8"))


def dur(path: Path) -> float:
    """Duration in seconds, or 0.0 if ffprobe can't read it."""
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "csv=p=0", str(path)],
        capture_output=True, text=True,
    ).stdout.strip()
    try:
        return float(out)
    except ValueError:
        return 0.0


async def render_line(out: Path, text: str, cfg: dict, tries: int = 4) -> None:
    """
    Render one line, retrying on transport failure.

    edge-tts talks to a Microsoft websocket endpoint that intermittently times out or
    drops the connection mid-stream — it failed on the first line of a run that had
    worked thirty seconds earlier. Without a retry a single blip aborts the whole
    episode, and a partially written mp3 is worse than none, so a failed attempt
    unlinks its own output before trying again.
    """
    import edge_tts

    for attempt in range(1, tries + 1):
        try:
            tts = edge_tts.Communicate(
                text, cfg["voice"], rate=cfg["rate"], pitch=cfg["pitch"]
            )
            await tts.save(str(out))
            if dur(out) > 0:
                return
            raise RuntimeError("wrote a file ffprobe cannot read")
        except Exception as exc:  # noqa: BLE001 - transport errors are varied
            out.unlink(missing_ok=True)
            if attempt == tries:
                raise
            wait = 2 * attempt
            print(f"      retry {attempt}/{tries - 1} in {wait}s ({type(exc).__name__})")
            await asyncio.sleep(wait)


async def main() -> None:
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    ep = sys.argv[1]
    force = "--force" in sys.argv
    report_only = "--report" in sys.argv

    sheet = load(ep)
    outdir = HERE / ep
    outdir.mkdir(parents=True, exist_ok=True)

    # ElevenLabs budget tracking. The narrator lines are billed per character and the
    # series has a hard ceiling, so this is counted rather than guessed.
    narr_chars = sum(len(l["text"]) for l in sheet["lines"] if l["who"] == "NARRATOR")

    print(f"{ep}: {len(sheet['lines'])} lines")
    print(f"  NARRATOR  {narr_chars} chars  -> ElevenLabs ({ELEVENLABS_VOICE})")

    todo = [l for l in sheet["lines"] if l["who"] != "NARRATOR"]
    print(f"  CHARACTERS {len(todo)} lines -> edge-tts (free)")

    if report_only:
        for l in sheet["lines"]:
            f = outdir / f"{l['id']}.mp3"
            mark = f"{dur(f):5.2f}s" if f.exists() else "   --  "
            print(f"    {mark}  {l['who']:<8} {l['id']:<12} {l['text'][:52]}")
        return

    made = skipped = 0
    for l in todo:
        who = l["who"]
        if who not in CAST:
            sys.exit(f"line {l['id']}: no casting for {who!r}")
        out = outdir / f"{l['id']}.mp3"
        if out.exists() and not force:
            skipped += 1
            continue
        await render_line(out, l["text"], CAST[who])
        print(f"    {dur(out):5.2f}s  {who:<8} {l['id']}")
        made += 1

    print(f"  rendered {made}, skipped {skipped}")

    missing = [l["id"] for l in sheet["lines"]
               if l["who"] == "NARRATOR" and not (outdir / f"narr-{l['id']}.mp3").exists()]
    if missing:
        print(f"\n  STILL NEEDED from ElevenLabs -> {outdir}/narr-<id>.mp3")
        for m in missing:
            print(f"    narr-{m}.mp3")


if __name__ == "__main__":
    asyncio.run(main())
