// ───────────────────────────────────────────────────────────────────────────
// 8b · hand-off snippets for the pwa agent (generated so they can never disagree with the files)
// ───────────────────────────────────────────────────────────────────────────
const media = (w, h, d) => `(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${d}) and (orientation: portrait)`
job('meta', 'store/splash-links.html', async () => Buffer.from(`<!-- iOS startup images (apple-touch-startup-image) — generated by scripts/make-icons.mjs.
     Paste inside <head>. Paths are relative so they work with vite base './'. Each file is a portrait splash at the exact
     device pixel size: carbon ${P.c0} field, the KIND badge, a faint dawn on the horizon. Set the manifest background_color
     and both theme-color metas to ${P.c0} so there is no flash between this image and first paint. -->
${SPLASH.map(([w, h, d, who]) => `<!-- ${who} -->\n<link rel="apple-touch-startup-image" media="${media(w, h, d)}" href="./splash/${splashName(w, h, d)}" />`).join('\n')}
`))

job('meta', 'store/head-tags.html', async () => Buffer.from(`<!-- Icons, social cards and colour — generated by scripts/make-icons.mjs. Paste inside <head>; replace SITE with the deployed origin. -->
<meta name="theme-color" content="${P.c0}" />
<meta name="color-scheme" content="dark" />
<link rel="icon" href="./favicon.ico" sizes="48x48" />
<link rel="icon" href="./favicon.svg" type="image/svg+xml" sizes="any" />
<link rel="icon" href="./favicon-32.png" type="image/png" sizes="32x32" />
<link rel="apple-touch-icon" href="./apple-touch-icon.png" />
<meta name="mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
<meta name="apple-mobile-web-app-title" content="KIND" />

<meta property="og:type" content="website" />
<meta property="og:site_name" content="KIND" />
<meta property="og:title" content="KIND — the daily family devotional" />
<meta property="og:description" content="Raising goDs. Building nations. One short launch a day: Scripture, one truth, a challenge and a prayer." />
<meta property="og:image" content="SITE/og.png" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta property="og:image:alt" content="The KIND badge above the Earth's horizon at sunrise, with the line Raising goDs. Building nations." />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:image" content="SITE/og-twitter.png" />
<meta name="twitter:image:alt" content="The KIND badge above the Earth's horizon at sunrise." />
`))

job('meta', 'store/manifest-icons.json', async () => Buffer.from(JSON.stringify({
  background_color: P.c0,
  theme_color: P.c0,
  icons: [
    { src: 'icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: 'icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    { src: 'icon-monochrome-512.png', sizes: '512x512', type: 'image/png', purpose: 'monochrome' },
    { src: 'icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
  ],
}, null, 2) + '\n'))
