// locker-journal behaviour pass: search, actions sheet, edit, delete, export. node playground/locker-journal.flow.mjs
import { open } from '../tools/browser.mjs'
const b = await open({ url: 'http://localhost:5183/playground/locker-journal.html?seed=15&now=2026-08-12', device: 'lowend', dpr: 2, state: null })
const { page } = b
const log = (k, v) => console.log(k, JSON.stringify(v))
await page.waitForSelector('.lcj-card')
// search
await page.fill('.lcj-search input', 'steward')
await page.waitForTimeout(200)
log('search steward', await page.evaluate(() => ({ meta: document.querySelector('.lcj-meta').innerText, cards: document.querySelectorAll('.lcj-card').length, marks: document.querySelectorAll('.lcj-mark').length })))
await page.fill('.lcj-search input', 'ese')   // folds Ẹ̀ṣẹ̀ ? (ẹ̀ṣẹ̀ -> eese) no: check 'ekan'
await page.fill('.lcj-search input', 'olorun')
await page.waitForTimeout(200)
log('search olorun (diacritic fold)', await page.evaluate(() => ({ meta: document.querySelector('.lcj-meta').innerText, marks: [...document.querySelectorAll('.lcj-mark')].map((m) => m.textContent) })))
await page.fill('.lcj-search input', 'zzzz')
await page.waitForTimeout(200)
log('search none', await page.evaluate(() => document.querySelector('.lcj-empty--none')?.innerText))
await page.click('.lcj-empty--none button')
await page.waitForTimeout(200)
// long entry + read more
await page.fill('.lcj-search input', 'paragraph')
await page.waitForTimeout(300)
log('long auto-open under search', await page.evaluate(() => ({ open: document.querySelector('.lcj-quote').hasAttribute('data-open'), h: document.querySelector('.lcj-quote__text').clientHeight })))
await page.fill('.lcj-search input', '')
await page.waitForTimeout(300)
const more = page.locator('.lcj-more')
log('more btn', await more.innerText())
await more.click(); await page.waitForTimeout(200)
log('after read more', await page.evaluate(() => ({ open: document.querySelector('.lcj-quote[data-open]') != null, label: document.querySelector('.lcj-more').innerText })))
await more.click()
// series filter
await page.locator('.lcj-chips .k-chip').nth(2).click(); await page.waitForTimeout(200)
log('filter longevity', await page.evaluate(() => ({ meta: document.querySelector('.lcj-meta').innerText, cards: document.querySelectorAll('.lcj-card').length })))
await page.locator('.lcj-chips .k-chip').nth(0).click()
// action sheet
await page.locator('.lcj-card').nth(2).locator('.k-iconbtn').click(); await page.waitForTimeout(700)
log('sheet', await page.evaluate(() => document.querySelector('[role=dialog]')?.innerText.slice(0, 200)))
await b.shot('lj-sheet')
await page.getByText('Edit', { exact: true }).click(); await page.waitForTimeout(900)
log('edit', await page.evaluate(() => ({ ta: document.querySelector('textarea')?.value.slice(0, 40), saveDisabled: [...document.querySelectorAll('[role=dialog] button')].find((x) => /save/i.test(x.innerText))?.disabled, dialogs: document.querySelectorAll('[role=dialog]').length })))
await page.fill('textarea', 'Edited: I will keep what I have been given with joy. Ẹ̀ṣẹ̀ steward.')
await b.shot('lj-edit')
await page.getByRole('button', { name: /save/i }).click(); await page.waitForTimeout(900)
log('after save', await page.evaluate(() => ({ first: document.querySelector('.lcj-card .lcj-quote__text').innerText, n: document.querySelectorAll('.lcj-card').length, dialogs: document.querySelectorAll('[role=dialog]').length })))
// delete
await page.locator('.lcj-card').first().locator('.k-iconbtn').click(); await page.waitForTimeout(600)
await page.getByText('Delete', { exact: true }).click(); await page.waitForTimeout(600)
log('confirm', await page.evaluate(() => document.querySelector('[role=alertdialog],[role=dialog]')?.innerText.slice(0, 160)))
await page.getByRole('button', { name: 'Keep it' }).click(); await page.waitForTimeout(400)
log('kept', await page.evaluate(() => document.querySelectorAll('.lcj-card').length))
await page.locator('.lcj-card').first().locator('.k-iconbtn').click(); await page.waitForTimeout(600)
await page.getByText('Delete', { exact: true }).click(); await page.waitForTimeout(600)
await page.getByRole('button', { name: 'Delete', exact: true }).click(); await page.waitForTimeout(600)
log('deleted', await page.evaluate(() => ({ n: document.querySelectorAll('.lcj-card').length, count: document.querySelector('.lcj-count__n').innerText, stored: Object.values(JSON.parse(localStorage.getItem('kind-app-v4')).series).reduce((n, s) => n + Object.keys(s.notes).length, 0) })))
// export
await page.getByRole('button', { name: 'Export' }).click(); await page.waitForTimeout(700)
const [dl] = await Promise.all([page.waitForEvent('download', { timeout: 4000 }).catch(() => null), page.getByText('Download .txt').click()])
log('download', dl ? dl.suggestedFilename() : null)
await page.waitForTimeout(500)
log('toast', await page.evaluate(() => document.body.innerText.includes('Journal saved')))
// overflow at 360
log('overflow', await page.evaluate(() => [...document.querySelectorAll('.lcj *')].filter((e) => e.getBoundingClientRect().right > innerWidth + 1).map((e) => e.className).slice(0, 5)))
console.log('errors', b.errors)
await b.close()
