import { open } from '../tools/browser.mjs'
const log = (k, v) => console.log(k, JSON.stringify(v))
const b = await open({ url: 'http://localhost:5183/playground/locker-journal.html?seed=15&now=2026-08-12', device: 'lowend', dpr: 2, state: null })
const { page } = b
await page.waitForSelector('.lcj-card')
log('buttons', await page.evaluate(() => document.querySelectorAll('.lcj-more').length))
await page.fill('.lcj-search input', 'steward'); await page.waitForTimeout(400)
log('search', await page.evaluate(() => ({ more: document.querySelectorAll('.lcj-more').length, open: document.querySelectorAll('.lcj-quote[data-open]').length })))
await page.fill('.lcj-search input', 'paragraph'); await page.waitForTimeout(400)
log('para', await page.evaluate(() => ({ more: document.querySelectorAll('.lcj-more').length, open: document.querySelectorAll('.lcj-quote[data-open]').length })))
await page.locator('.lcj-more').click(); await page.waitForTimeout(200)
log('collapse manual', await page.evaluate(() => document.querySelectorAll('.lcj-quote[data-open]').length))
await page.fill('.lcj-search input', ''); await page.waitForTimeout(300)
log('empty-ok', await page.evaluate(() => document.querySelectorAll('.lcj-card').length))
await b.close()
const e = await open({ url: 'http://localhost:5183/playground/locker-journal.html?seed=0&now=2026-08-12', device: 'lowend', dpr: 2, state: null })
log('empty box', await e.page.evaluate(() => { const r = document.querySelector('.k-empty').getBoundingClientRect(); return [Math.round(r.left), Math.round(r.right), innerWidth] }))
await e.shot('lj-empty2', { settle: 500 })
log('errors', [...b.errors, ...e.errors])
await e.close()
