import { open } from '../tools/browser.mjs'
const base = 'http://localhost:5183/playground/shorts-reel.html'
let b = await open({ url: base + '?series=secrets-of-longevity&fx=lite', now: '2026-07-12', device: 'lowend', dpr: 2 })
await b.page.waitForTimeout(800)
await b.page.focus('.sho-scroll'); await b.page.keyboard.press('ArrowDown'); await b.page.waitForTimeout(1500)
await b.shot('shorts-reel/poster-lite-360')
console.log('foot/hex', await b.page.evaluate(() => { const g = (s) => { const r = document.querySelector('.sho-reel[data-active] ' + s)?.getBoundingClientRect(); return r && [Math.round(r.top), Math.round(r.bottom)] }; return { hex: g('.k-hex'), title: g('.sho-title'), actions: g('.sho-actions'), hint: g('.sho-hint') } }))
console.log('errors', JSON.stringify(b.errors)); await b.close()
b = await open({ url: base + '?spec=1&series=secrets-of-longevity', device: 'iphone', dpr: 2 })
await b.page.waitForTimeout(1200)
await b.shot('shorts-reel/lyt-spec')
const box = await b.page.evaluate(() => [...document.querySelectorAll('.lyt')].map((e) => { const r = e.getBoundingClientRect(); return [Math.round(r.width), Math.round(r.height)] }))
console.log('lyt boxes', JSON.stringify(box))
await b.page.click('.lyt .lyt-hit'); await b.page.waitForTimeout(800)
console.log('after tap', await b.page.evaluate(() => ({ iframes: document.querySelectorAll('iframe').length, state: document.querySelector('.lyt').dataset.state, box: (() => { const r = document.querySelector('.lyt').getBoundingClientRect(); return [Math.round(r.width), Math.round(r.height)] })() })))
console.log('errors', JSON.stringify(b.errors)); await b.close()
b = await open({ url: base + '?series=stewardship-code', now: '2026-08-12', device: 'iphone', dpr: 2 })
await b.page.waitForTimeout(800)
console.log('live order', await b.page.evaluate(() => [...document.querySelectorAll('.sho-item')].map((i) => i.getAttribute('aria-label').match(/Day (\d+)/)[1]).join(',')))
console.log('errors', JSON.stringify(b.errors)); await b.close()
